
CREATE TABLE orders (
	id INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	quantity INT UNSIGNED NOT NULL,
	cost INT UNSIGNED NOT NULL,
	entered TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	paid TIMESTAMP NULL DEFAULT NULL,
	mailed TIMESTAMP NULL DEFAULT NULL,
	name VARCHAR(50) NOT NULL,
	email VARCHAR(255) NOT NULL,
	street VARCHAR(100) NOT NULL,
	postcode CHAR(5) NOT NULL,
	postoffice VARCHAR(30) NOT NULL,
	confirm_id CHAR(40) NOT NULL
)
	CHARACTER SET utf8
	COLLATE utf8_general_ci
	ENGINE InnoDB
;

